REGEX = '(?<!\w\.\w.)(?<![A-Z][a-z]\.)(?<=\.|\?)\s'
NAME = 'Helsinki-NLP/opus-mt-es-ca'
NAME_ONNX = 'onnx/test.onnx'
FEATURE = 'seq2seq-lm'
OPSET = 12
ATOL = 1e-5
MAX_LENGTH = 50
EMBEDDING_SIZE = 512
BATCH_SIZE = 1
PAST_KEY_VALUES_DEFAULT_TOKEN = 0
ITERATIONS = 10
